language: go
sudo: false

before_install:
    - go get golang.org/x/lint/golint
    - go get honnef.co/go/tools/cmd/megacheck
    - go get github.com/mdempsky/unconvert
    - go get github.com/mdempsky/maligned

script:
    - golint -set_exit_status ./...
    - megacheck ./...
    - unconvert ./...
    - maligned ./...
    - go vet ./...
    - go test -race -v ./...

go:
    - 1.10.x
    - 1.11.x
    - tip

os:
    - linux
    - osx
