[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/mortdeus/go9p"

[[constraint]]
  branch = "master"
  name = "github.com/nsf/termbox-go"

[[constraint]]
  branch = "master"
  name = "github.com/ravernkoh/deepl"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  branch = "master"
  name = "google.golang.org/api"
