on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'
name: CI

jobs:
  test:
    name: Lint and test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go: [1.23.x]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up GOBIN
      run: |
        echo ::add-path::{{ github.workspace }}/bin
        echo ::set-env name=GOBIN={{ github.workspace }}/bin
    - name: Test
      run: go test -race ./...
    - name: golint
      run: |
        go install golang.org/x/lint/golint
        ./bin/golint -set_exit_status ./...
    - name: unconvert
      run: |
        go install github.com/mdempsky/unconvert
        ./bin/unconvert -v ./...
    - name: maligned
      run: |
        go install github.com/mdempsky/maligned
        ./bin/maligned ./...
    - name: staticcheck
      run: |
        go install honnef.co/go/tools/cmd/staticcheck
        ./bin/staticcheck ./...
